using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using ByteSizeLib;
using Konsole;
using Newtonsoft.Json;
using Shared;
using Shared.Models;
using Colors = Shared.Colors;

namespace BuildBackup.DebugUtil
{
    public class ComparisonUtil
    {
        private readonly IConsole _console;
        private readonly Mapper mapper;

        //TODO extract url to settings
        string _blizzardCdnBaseUri = "http://level3.blizzard.com";
        public ComparisonUtil(IConsole console)
        {
            this._console = console;
            var mapperConfig = new MapperConfiguration(cfg => cfg.CreateMap<Request, ComparedRequest>());
            mapper = new Mapper(mapperConfig);
        }
        
        public ComparisonResult CompareAgainstRealRequests(List<Request> allRequestsMade, TactProduct product)
        {
            Console.WriteLine("Comparing requests against real request logs...");
            var timer = Stopwatch.StartNew();

            var fileSizeProvider = new FileSizeProvider(product);
            var realRequests = NginxLogParser.ParseRequestLogs(Config.LogFileBasePath, product);

            var comparisonResult = new ComparisonResult
            {
                //Hits = diffResult.MatchedRequests,
                //Misses = diffResult.MissedRequests,

                RequestMadeCount = allRequestsMade.Count,
                RealRequestCount = realRequests.Count,

                RealRequestsTotalSize = ByteSize.FromBytes((double)realRequests.Sum(e => e.TotalBytes)),

                RequestsWithoutSize = allRequestsMade.Count(e => e.DownloadWholeFile),
                RealRequestsWithoutSize = realRequests.Count(e => e.TotalBytes == 0)
            };

            PreLoadHeaderSizes(allRequestsMade, product);
            GetRequestSizes(allRequestsMade, fileSizeProvider);
            comparisonResult.RequestTotalSize = ByteSize.FromBytes((double) allRequestsMade.Sum(e => e.TotalBytes));
            
            CompareRequests(allRequestsMade, realRequests);
            comparisonResult.Misses = realRequests;
            comparisonResult.UnnecessaryRequests = allRequestsMade;

            comparisonResult.PrintOutput();

            Console.WriteLine($"Comparison complete! {Colors.Yellow(timer.Elapsed.ToString(@"mm\:ss\.FFFF"))}");
            return comparisonResult;
        }

        private void GetRequestSizes(List<Request> allRequestsMade, FileSizeProvider fileSizeProvider)
        {
            foreach (var request in allRequestsMade)
            {
                if (request.DownloadWholeFile)
                {
                    request.DownloadWholeFile = false;
                    request.LowerByteRange = 0;
                    // Subtracting 1, because it seems like the byte ranges are "inclusive".  Ex range 0-9 == 10 bytes length.
                    request.UpperByteRange = fileSizeProvider.GetContentLength(new Uri($"{_blizzardCdnBaseUri}/{request.Uri}")) - 1;
                }
            }
        }

        private DiffResults FindExcessRequests(List<Request> requests, List<Request> realRequests, FileSizeProvider fileSizeProvider)
        {
            var deduped = requests.ToList();
            //var deduped = requests.GroupBy(e => new {e.LowerByteRange, e.UpperByteRange, e.Uri}).Select(e => e.First()).ToList();
            // Making a copy of the requests our app made.  
            var generatedRequests = FastDeepCloner.DeepCloner.Clone(deduped);
            // Updating the byte range requested, so we can later determine what parts of the request are unnecessary
            foreach (var request in generatedRequests)
            {
                if (request.DownloadWholeFile)
                {
                    request.DownloadWholeFile = false;
                    request.LowerByteRange = 0;
                    // Subtracting 1, because it seems like the byte ranges are "inclusive".  Ex range 0-9 == 10 bytes length.
                    request.UpperByteRange = fileSizeProvider.GetContentLength(new Uri($"{_blizzardCdnBaseUri}/{request.Uri}")) - 1;
                }
            }
            fileSizeProvider.Save();

            // These are going to be the actual requests generated by Battle.net.  Will mark them as either matched/unmatched
            var realRequestsMatched = realRequests.Select(e => mapper.Map<ComparedRequest>(e)).ToList();

            // Taking each "real" request, and "subtracting" it from the requests our app made.  Hoping to figure out what excess is being left behind.
            foreach (var realReq in realRequestsMatched)
            {
                // Exact match, simply remove from the list and marked as found
                var exactMatches = generatedRequests.Where(e => e.Uri == realReq.Uri
                                                              && e.LowerByteRange == realReq.LowerByteRange
                                                              && e.UpperByteRange == realReq.UpperByteRange).ToList();
                if (exactMatches.Any())
                {
                    if (exactMatches.Count > 1)
                    {
                        //TODO
                        //Debugger.Break();
                    }
                    realReq.Matched = true;
                    generatedRequests.Remove(exactMatches[0]);
                    continue;
                }
                var rangeMatches = generatedRequests.Where(e => e.Uri == realReq.Uri
                                                              && realReq.LowerByteRange >= e.LowerByteRange 
                                                              && realReq.UpperByteRange <= e.UpperByteRange).ToList();
                if (rangeMatches.Any())
                {
                    if (rangeMatches.Count > 1)
                    {
                        //TODO how do I handle this scenario?
                    }
                    // Breaking up into two new slices
                    var lowerSlice = new Request
                    {
                        Uri = rangeMatches[0].Uri,
                        LowerByteRange = rangeMatches[0].LowerByteRange,
                        UpperByteRange = realReq.LowerByteRange - 1,
                        CallingMethod = rangeMatches[0].CallingMethod
                    };
                    var upperSlice = new Request
                    {
                        Uri = rangeMatches[0].Uri,
                        LowerByteRange = realReq.UpperByteRange + 1,
                        UpperByteRange = rangeMatches[0].UpperByteRange,
                        CallingMethod = rangeMatches[0].CallingMethod
                    };
                    generatedRequests.Add(lowerSlice);
                    generatedRequests.Add(upperSlice);

                    realReq.Matched = true;
                    generatedRequests.Remove(rangeMatches[0]);
                    continue;
                }
                // Special case for indexes
                if (realReq.Uri.Contains(".index"))
                {
                    var indexMatches = generatedRequests.Where(e => e.Uri == realReq.Uri).ToList();
                    if (indexMatches.Any())
                    {
                        realReq.Matched = true;
                        generatedRequests.Remove(indexMatches[0]);
                    }
                   
                    continue;
                }
            }

            var findExcessRequests = new DiffResults()
            {
                MatchedRequests = realRequestsMatched.Where(e => e.Matched).ToList(),
                MissedRequests = realRequestsMatched.Where(e => e.Matched == false).OrderBy(e => e.Uri).ThenBy(e => e.LowerByteRange).ToList(),

                UnnecessaryRequests = generatedRequests.ToList()
            };

            var missedGroups = findExcessRequests.MissedRequests.GroupBy(e => e.Uri).Where(e => e.Count() > 10).OrderByDescending(e => e.Count()).ToList();
            foreach (var group in missedGroups)
            {
                Console.WriteLine($"Missed {Colors.Yellow(group.Count())} requests for uri {Colors.Magenta(group.Key)} Size : {ByteSize.FromBytes(group.Sum(e => e.TotalBytes))}");
            }

            File.Delete(@"C:\Users\Tim\Dropbox\Programming\dotnet-public\BattleNetBackup\allRequests.json");
            File.WriteAllText(@"C:\Users\Tim\Dropbox\Programming\dotnet-public\BattleNetBackup\allRequests.json", JsonConvert.SerializeObject(requests));

            File.Delete(@"C:\Users\Tim\Dropbox\Programming\dotnet-public\BattleNetBackup\excessRequests.json");
            File.WriteAllText(@"C:\Users\Tim\Dropbox\Programming\dotnet-public\BattleNetBackup\excessRequests.json", JsonConvert.SerializeObject(generatedRequests.ToList()));

            return findExcessRequests;
        }

        public void CompareRequests(List<Request> generatedRequests, List<Request> originalRequests)
        {
            // Copying the original requests to a temporary list, so that we can remove entries without modifying the enumeration
            var requestsToProcess = new List<Request>(originalRequests.Count);
            foreach (var request in originalRequests)
            {
                requestsToProcess.Add(request);
            }
            originalRequests.Clear();

            // Taking each "real" request, and "subtracting" it from the requests our app made.  Hoping to figure out what excess is being left behind.
            while(requestsToProcess.Any())
            {
                var current = requestsToProcess.First();

                // Special case for indexes
                if (current.Uri.Contains(".index"))
                {
                    var indexMatches = generatedRequests.Where(e => e.Uri == current.Uri).ToList();
                    if (indexMatches.Any())
                    {
                        requestsToProcess.RemoveAt(0);
                        generatedRequests.Remove(indexMatches[0]);
                    }

                    continue;
                }

                // Exact match, remove from both lists
                var exactMatches = generatedRequests.Where(e => e.Uri == current.Uri
                                                              && e.LowerByteRange == current.LowerByteRange
                                                              && e.UpperByteRange == current.UpperByteRange).ToList();
                if (exactMatches.Any())
                {
                    if (exactMatches.Count > 1)
                    {
                        //TODO
                        //Debugger.Break();
                    }

                    requestsToProcess.RemoveAt(0);
                    generatedRequests.Remove(exactMatches[0]);
                    continue;
                }

                var rangeMatches = generatedRequests.Where(e => e.Uri == current.Uri
                                                              && current.LowerByteRange >= e.LowerByteRange
                                                              && current.UpperByteRange <= e.UpperByteRange).ToList();
                if (rangeMatches.Any())
                {
                    if (rangeMatches.Count > 1)
                    {
                        //TODO how do I handle this scenario?
                    }
                    // Breaking up the remainder into new slices

                    if (rangeMatches[0].LowerByteRange != current.LowerByteRange)
                    {
                        var lowerSlice = new Request
                        {
                            Uri = rangeMatches[0].Uri,
                            //TODO should probably unit test the range calculations as well
                            LowerByteRange = rangeMatches[0].LowerByteRange,
                            UpperByteRange = current.LowerByteRange - 1,
                            CallingMethod = rangeMatches[0].CallingMethod
                        };
                        generatedRequests.Add(lowerSlice);
                    }
                    
                    // Only add an upper slice, if there is any remaining bytes to do so.
                    if (rangeMatches[0].UpperByteRange != current.UpperByteRange)
                    {
                        var upperSlice = new Request
                        {
                            Uri = rangeMatches[0].Uri,
                            //TODO should probably unit test the range calculations as well
                            LowerByteRange = current.UpperByteRange + 1,
                            UpperByteRange = rangeMatches[0].UpperByteRange,
                            CallingMethod = rangeMatches[0].CallingMethod
                        };
                        generatedRequests.Add(upperSlice);
                    }
                    generatedRequests.Remove(rangeMatches[0]);

                    requestsToProcess.RemoveAt(0);
                    continue;
                }

                var partialMatchesLower = generatedRequests.Where(e => e.Uri == current.Uri 
                                                                  && current.LowerByteRange <= e.UpperByteRange
                                                                  && current.UpperByteRange >= e.UpperByteRange).ToList();
                if (partialMatchesLower.Any())
                {
                    // Store the originals, since we need to swap them
                    var originalUpper = partialMatchesLower[0].UpperByteRange;
                    var originalLower = current.LowerByteRange;

                    // Now swap them
                    partialMatchesLower[0].UpperByteRange = originalLower - 1;
                    current.LowerByteRange = originalUpper + 1;
                    continue;
                }

                var partialMatchesUpper = generatedRequests.Where(e => e.Uri == current.Uri
                                                                       && current.UpperByteRange >= e.LowerByteRange
                                                                       && current.LowerByteRange <= e.LowerByteRange).ToList();
                if (partialMatchesUpper.Any())
                {
                    // Store the originals, since we need to swap them
                    var originalUpper = current.UpperByteRange;
                    var originalLower = partialMatchesUpper[0].LowerByteRange; 

                    // Now swap them
                    partialMatchesUpper[0].LowerByteRange = originalUpper + 1;
                    current.UpperByteRange = originalLower - 1;
                    continue;
                }

                

                // No match found - Put it back into the original array, as a "miss"
                requestsToProcess.RemoveAt(0);
                originalRequests.Add(current);
            }
        }

        private void PreLoadHeaderSizes(List<Request> requests, TactProduct product)
        {
            //TODO log that this is processing X of N 
            //TODO speed up the initial processing
            var fileSizeProvider = new FileSizeProvider(product);

            // Speeding up by pre-caching the content-length headers in parallel.
            var wholeFileRequests = requests.Where(e => e.DownloadWholeFile).OrderBy(e => e.Uri).ToList();

            var progressBar = new ProgressBar(_console, PbStyle.SingleLine, wholeFileRequests.Count, 50);
            int count = 0;
            Parallel.ForEach(wholeFileRequests, new ParallelOptions { MaxDegreeOfParallelism = 20 }, request =>
            {
                fileSizeProvider.GetContentLength(new Uri($"{_blizzardCdnBaseUri}/{request.Uri}"));
                progressBar.Refresh(count, $"Getting request sizes");
                count++;
            });
            fileSizeProvider.Save();
        }

        private ByteSize CalculateRequestSizes(List<Request> requests, TactProduct product)
        {
            //TODO log that this is processing X of N 
            //TODO speed up the initial processing
            var fileSizeProvider = new FileSizeProvider(product);
            
            // Speeding up by pre-caching the content-length headers in parallel.
            var wholeFileRequests = requests.Where(e => e.DownloadWholeFile).OrderBy(e => e.Uri).ToList();
            Parallel.ForEach(wholeFileRequests, new ParallelOptions { MaxDegreeOfParallelism = 20 }, request =>
            {
                fileSizeProvider.GetContentLength(new Uri($"{_blizzardCdnBaseUri}/{request.Uri}"));
            });
            fileSizeProvider.Save();

            // Actually summing up the total request size
            long totalBytes = requests.Sum(e => e.TotalBytes);
            foreach (var request in wholeFileRequests)
            {
                totalBytes += fileSizeProvider.GetContentLength(new Uri($"{_blizzardCdnBaseUri}/{request.Uri}"));
            }
            
            return ByteSize.FromBytes(totalBytes);
        }
    }
}